restore-previous-power-state: Halt on errors

diff --git a/restore-previous-power-state b/restore-previous-power-state
--- a/restore-previous-power-state
+++ b/restore-previous-power-state
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# Halt on errors
+set -e
+
 PREVIOUS_STATE_FILE=/var/lib/pm-utils/previous_state
 
 if [ ${UID} -ne 0 ]; then
